export { default as About } from './About'
export { default as Footer } from './Footer'
export { default as Form } from './Form'
export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as HowWorks } from './HowWorks'
export { default as Price } from './Price'
export { default as Faq } from './Faq'